spring.application.name=jobportalapplication

# =========================
# DATABASE (AWS RDS MySQL)
# =========================
spring.datasource.url=jdbc:mysql://jobportal-db.c9cogymc435n.ap-south-1.rds.amazonaws.com:3306/jobportal-db?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =========================
# JWT CONFIG
# =========================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# =========================
# GEMINI AI CONFIG
# =========================
gemini.api.key=${GEMINI_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# =========================
# CASHFREE (LIVE)
# =========================
cashfree.client_id=${CASHFREE_CLIENT_ID}
cashfree.client_secret=${CASHFREE_CLIENT_SECRET}
cashfree.env=prod

# =========================
# SERVER
# =========================
server.port=${PORT:8080}
# =========================
# HIKARI CONNECTION POOL (FIX TOO MANY CONNECTIONS)
# =========================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.leak-detection-threshold=60000
